version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d